http:
  port: "8081"
  host: "localhost"


db:
  host: "sql6.freemysqlhosting.net"
  port: "3306"
  username: "sql6447382" 
  password: "qBqewZ1CGl"
  database-name: "sql6447382"
  reconnection-strategy-frequency-ms : "2000"
  reconnection-strategy-attempts : "2"
  
  
mule:
  env: "dev"
  
soap:
  wsdlLocation: "http://localhost:8081/ticket-booking-service/ticket-booking-serviceSOAP?wsdl"
  address: "http://localhost:8081/ticket-booking-service/ticket-booking-serviceSOAP"
  service: "ticket-booking-service"
  port: "ticket-booking-serviceSOAP"
  wsdlFileLocation: "bookmyshow-order-management.wsdl"

json:
  logger:
    application:
      name: "test"
      version: "test"